# NUMPY tutorial

funcrtions that RETURNS a COPY, executed as methods and attributes........if function is an attribute then , it can be called through DEFINED VARIABLE(x.abc()) ....... otherwise its a method(np.abc())

In [2]:
import numpy as np

In [2]:
x=np.array([1,2,3])

In [3]:
y=np.array([42,23,21])

# x

## 2d array 

In [4]:
two_d=np.array([x,[4,5,6]])

In [5]:
two_d

array([[1, 2, 3],
       [4, 5, 6]])

## 3d array 

In [6]:
threed=np.array([[[1,2,3],[4,5,6],[7,8,9]]] )
threed

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# conversion numpy to list (vice versa)

In [7]:
n1=np.arange(5)
n2=np.arange(2,10)
n3=np.arange(2,10,2)


In [8]:
n1

array([0, 1, 2, 3, 4])

In [9]:
n2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
n3

array([2, 4, 6, 8])

In [11]:
type(n3)

numpy.ndarray

## NUMPY to LIST

In [12]:
backtolist=n3.tolist()

In [13]:
type(backtolist)

list

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# # linspace()     for evenly spaced sequence

In [15]:
np.linspace(4,12,5)

array([ 4.,  6.,  8., 10., 12.])

In [16]:
np.linspace(4,12,5,endpoint=True)

array([ 4.,  6.,  8., 10., 12.])

In [17]:
np.linspace(4,12,5,retstep=True)  # REturn step intervals

(array([ 4.,  6.,  8., 10., 12.]), 2.0)

# rand and randint functiond differ

In [18]:
randoms=np.random.randint(12,24,[5,6])

In [19]:
print(randoms)

[[12 22 23 20 14 13]
 [22 12 17 18 18 14]
 [15 12 16 16 16 14]
 [21 18 23 18 14 19]
 [14 12 15 23 13 23]]


# eye () VS identity() IDENTICAL matrix 

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.eye(4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# attributes information  (NO PARAMETERS/ BRACKETS)

In [23]:
randoms.itemsize

4

In [24]:
randoms.ndim

2

In [25]:
randoms.size

30

In [26]:
randoms.shape

(5, 6)

# numpy & list concatenation

In [27]:
l1 =[12,23,44]
l2=[32,43,54]
l3=[54,22,60]

In [28]:
l4=l2+l3
l4

[32, 43, 54, 54, 22, 60]

In [29]:
z=x+y
z

array([43, 25, 24])

In [30]:
z.shape

(3,)

In [31]:
z.reshape(3,1)

array([[43],
       [25],
       [24]])

# resize() .... differ from reshape() ??

# The difference between them is that the reshape() does not changes the original array but only returns the changed array, whereas the resize() method returns nothing and directly changes the original array

In [ ]:
np.resize()

# COPY FUNCTION

In [33]:
x

array([1, 2, 3])

In [34]:
a=x
a

array([1, 2, 3])

In [36]:
x[0]=222
x

array([222,   2,   3])

In [39]:
a[0]=2345       ## CHANGES are reflected in a also

In [40]:
a

array([2345,    2,    3])

In [42]:
x    ### CHANGES are reverted to original array ALSO

array([2345,    2,    3])

In [44]:
b=x.copy()

In [45]:
x[0]=987

In [47]:
b    # np.ndarray.base

array([2345,    2,    3])

### GO THROUGH np.copy() vs copy.deepcopy()

# view()

 view(): changes made to view will affect the original array, VIEW IS JUST A VIEW OF ORIGINAL ARRAY.........................................................................................
  copy() : any changes made to copy will not affect original array, COPY IS A NEW ARRAY    

In [48]:
x

array([987,   2,   3])

In [49]:
c=x.view()
c[1]=1000
c

array([ 987, 1000,    3])

In [50]:
x

array([ 987, 1000,    3])

# flatten()

In [52]:
flat=two_d.flatten()
flat

array([1, 2, 3, 4, 5, 6])

In [53]:
two_d

array([[1, 2, 3],
       [4, 5, 6]])

# ARITHMETIC() within single array

# # SUM()   

In [55]:
n1

array([0, 1, 2, 3, 4])

In [56]:
n2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
n2.resize(4,2)

In [64]:
n2

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [65]:
n2.sum(axis=1)

array([ 5,  9, 13, 17])

In [68]:
# SIMIlarly for PROD(), SORT(axis=0)

# vstack()....MERGING

### NOTE: in brackets tuple must be passed

In [69]:
a1=np.array([23,56,23])
a2=np.array([25,87,93])     
np.vstack((a1,a2))


array([[23, 56, 23],
       [25, 87, 93]])

In [71]:
np.hstack((a1,a2))

array([23, 56, 23, 25, 87, 93])

# SPLIT....... split into equal size

In [89]:
r1=np.arange(2,14)
r1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [90]:
np.split(r1,2)

[array([2, 3, 4, 5, 6, 7]), array([ 8,  9, 10, 11, 12, 13])]

In [98]:
np.split(r1,[3])          # to split at defined index

[array([2, 3, 4]), array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])]

In [99]:
np.split(r1,[3,6])  

[array([2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10, 11, 12, 13])]